name: Daily YouTube Update

on:
  schedule:
    - cron: '35 3,4 * * *'  # Runs at 3:35 and 4:35 UTC (8:35 PM LA time year-round)
  workflow_dispatch:  # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # This ensures we have the full history
        
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        echo "YOUTUBE_API_KEY_1=${{ secrets.YOUTUBE_API_KEY_1 }}" > .env
        echo "YOUTUBE_API_KEY_2=${{ secrets.YOUTUBE_API_KEY_2 }}" >> .env
        
    - name: Run YouTube tracker
      run: python daily_fetcher.py
      
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Commit and push if changed
      run: |
        git add templates/index.html
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update YouTube data $(date +'%Y-%m-%d')" && git push) 